version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - ktm_network
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - '$DB_PORT:$DB_PORT'

  pgadmin:
    image: dpage/pgadmin4:7.0
    depends_on:
      - postgres
    networks:
      - ktm_network
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - '8080:8080'
    environment:
      PGADMIN_DEFAULT_EMAIL: daniel@email.com
      PGADMIN_DEFAULT_PASSWORD: P@ssword1234
    env_file:
      - .env

  # ktmcore:
  #   image: ktmcore:1.0.0
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - ktm_network

networks:
  ktm_network:
    driver: bridge
